version: "3"

services:
  database:
    image: postgres:14.5-alpine

    ports:
      - "23456:5432"

    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}

    volumes:
      - type: volume
        source: database-content
        target: /var/lib/postgresql/data

volumes:
  database-content:
